apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team : frontend
    version : 1.4.5
    environment : production
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80